### ISSUE TITLE
Exception in get_remote_binlog. bin2decimal() failed

### ISSUE THREAD

**Issue by Sunsh1neRus** [tarantool/libslave#6]
Commit a01c09d
MySQL 5.7
`[2017-05-06 08:31:37] E Met exception in get_remote_binlog cycle. Message: Field_decimal::unpack(): bin2decimal() failed`

**Comment by deadbabe** [comment]
Is it ok now?

**Comment by tcexe** [comment]
no, it's not. Same error

**Comment by tcexe** [comment]
I agree

**Comment by Sunsh1neRus** [comment]
I agree

**Comment by deadbabe** [comment]
Can't reproduce with my test setup. Must be something in you binlog. Running with verbose loggin (uncomment everything in `Logging.h`) might help clarifying the problem.

**Comment by Sunsh1neRus** [comment]
It is ok now. I deleted the position of binlog in tarantool. All records from mysql replicated in tarantool. Thanks so much for your helping

**Comment by deadbabe** [comment]
So it's ok now, can be closed?
